-- 1. Create Public Profiles Table (Mirrors auth.users to allow public access and joins)
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. RLS for Profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone." 
  on public.profiles for select using (true);

create policy "Users can insert their own profile." 
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update own profile." 
  on public.profiles for update using (auth.uid() = id);

-- 3. Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing; -- Prevent error if already exists
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to ensure clean slate
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 4. Backfill existing users (Helper function)
create or replace function backfill_profiles()
returns void as $$
begin
  insert into public.profiles (id, email)
  select id, email from auth.users
  where id not in (select id from public.profiles);
end;
$$ language plpgsql security definer;

-- Run backfill immediately
select backfill_profiles();


-- 5. Update Messages table foreign keys
-- Add FK from messages.sender_id to profiles.id
-- This allows PostgREST to embed profiles easily without 400 errors (since auth.users is closed).
do $$ 
begin
  if not exists (select 1 from information_schema.table_constraints where constraint_name = 'messages_sender_profile_fkey') then
    alter table messages add constraint messages_sender_profile_fkey 
      foreign key (sender_id) references public.profiles(id);
  end if;
end $$;


-- 6. Friend/Connection System
create table if not exists user_connections (
  id bigint generated by default as identity primary key,
  requester_id uuid references public.profiles(id) not null,
  receiver_id uuid references public.profiles(id) not null,
  status text check (status in ('pending', 'accepted', 'rejected', 'blocked')) default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(requester_id, receiver_id)
);

alter table user_connections enable row level security;

-- Policy: View connections (requests sent or received)
create policy "View connections" on user_connections
  for select using (auth.uid() = requester_id or auth.uid() = receiver_id);

-- Policy: Send request
create policy "Insert connection request" on user_connections
  for insert with check (auth.uid() = requester_id);

-- Policy: Update status (Accept/Reject)
create policy "Update connection" on user_connections
  for update using (auth.uid() = receiver_id or auth.uid() = requester_id);
