-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- 1. PROJECTS TABLE
create table if not exists projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  owner_id uuid references auth.users(id) not null,
  gsc_property_url text, -- Search Console Property URL
  settings jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. PROJECT MEMBERS TABLE
create table if not exists project_members (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  user_id uuid references auth.users(id) not null,
  role text check (role in ('admin', 'editor', 'viewer')) default 'editor',
  status text check (status in ('active', 'pending')) default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(project_id, user_id)
);

-- 3. PROJECT INVITES TABLE (For non-registered or pending users)
create table if not exists project_invites (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  email text not null,
  role text default 'editor',
  token uuid default uuid_generate_v4(),
  invited_by uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone not null,
  unique(project_id, email)
);

-- 4. TASKS TABLE
create table if not exists tasks (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  title text not null,
  description text,
  status text default 'idea', -- 'idea', 'todo', 'in_progress', 'review', 'done'
  priority text default 'medium', -- 'low', 'medium', 'high', 'critical'
  assignee_id uuid references auth.users(id),
  due_date timestamp with time zone,
  
  -- SEO Specifics
  target_keyword text,
  target_url_slug text,
  
  -- Tool Integration Context
  associated_url text, -- If linked to a sitemap URL
  
  created_by uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. TASK ARTIFACTS (Linking ContentWriter drafts, BlogViz images to tasks)
create table if not exists task_artifacts (
  id bigint generated by default as identity primary key,
  task_id bigint references tasks(id) on delete cascade not null,
  artifact_type text not null, -- 'draft', 'image', 'report'
  artifact_ref_id text not null, -- ID of the external item (draft_id, etc.)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. SITEMAP URLS (For caching project URLs)
create table if not exists sitemap_urls (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  url text not null,
  category text, 
  last_crawled_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(project_id, url)
);

-- RLS POLICIES (Simplified for MVP - assuming standard auth)

alter table projects enable row level security;
alter table project_members enable row level security;
alter table project_invites enable row level security;
alter table tasks enable row level security;
alter table task_artifacts enable row level security;
alter table sitemap_urls enable row level security;

-- Policy: Users can view projects they are members of (or owners)
create policy "Users can view own projects" on projects
  for select using (
    auth.uid() = owner_id or 
    exists (select 1 from project_members where project_id = projects.id and user_id = auth.uid())
  );

create policy "Users can insert own projects" on projects
  for insert with check (auth.uid() = owner_id);

create policy "Users can update own projects" on projects
  for update using (
    auth.uid() = owner_id or
    exists (select 1 from project_members where project_id = projects.id and user_id = auth.uid() and role = 'admin')
  );

-- Policy: Members visibility
create policy "View members" on project_members
  for select using (
    exists (select 1 from projects p where p.id = project_members.project_id and (p.owner_id = auth.uid() or exists (select 1 from project_members pm where pm.project_id = p.id and pm.user_id = auth.uid())))
  );

-- Policy: Tasks visibility
create policy "View tasks" on tasks
  for select using (
    exists (select 1 from project_members where project_id = tasks.project_id and user_id = auth.uid()) or
    exists (select 1 from projects where id = tasks.project_id and owner_id = auth.uid())
  );

create policy "Manage tasks" on tasks
  for all using (
    exists (select 1 from project_members where project_id = tasks.project_id and user_id = auth.uid()) or
    exists (select 1 from projects where id = tasks.project_id and owner_id = auth.uid())
  );
