-- Tabla para gestionar API Keys de usuario
create table if not exists user_api_keys (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  provider text not null, -- 'gemini', 'serper', 'valueserp', 'jina'
  key_value text not null,
  label text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table user_api_keys enable row level security;

-- Políticas de seguridad
drop policy if exists "Users can view own keys" on user_api_keys;
create policy "Users can view own keys" on user_api_keys for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert own keys" on user_api_keys;
create policy "Users can insert own keys" on user_api_keys for insert with check ( auth.uid() = user_id );

drop policy if exists "Users can delete own keys" on user_api_keys;
create policy "Users can delete own keys" on user_api_keys for delete using ( auth.uid() = user_id );

drop policy if exists "Users can update own keys" on user_api_keys;
create policy "Users can update own keys" on user_api_keys for update using ( auth.uid() = user_id );
