-- INVITATIONS AND NOTIFICATIONS SYSTEM V2

-- 1. Ensure project_invites table exists and has correct columns
create table if not exists project_invites (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  email text not null,
  role text not null default 'editor', -- 'admin', 'editor', 'viewer'
  invited_by uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone,
  
  -- Prevent duplicate invites for same project/email
  constraint unique_project_email unique(project_id, email)
);

-- 2. RLS for project_invites
alter table project_invites enable row level security;

-- Policy: Admin/Owner can View
create policy "Admins View Invites" on project_invites
  for select using (
    exists (select 1 from projects where id = project_invites.project_id and owner_id = auth.uid()) or
    exists (select 1 from project_members where project_id = project_invites.project_id and user_id = auth.uid() and role = 'admin')
  );

-- Policy: Invited User can View (by email matching their auth email)
create policy "Invited Users View Invites" on project_invites
  for select using (
    email = (select email from auth.users where id = auth.uid())
  );

-- Policy: Admin/Owner can Insert
create policy "Admins Insert Invites" on project_invites
  for insert with check (
    exists (select 1 from projects where id = project_invites.project_id and owner_id = auth.uid()) or
    exists (select 1 from project_members where project_id = project_invites.project_id and user_id = auth.uid() and role = 'admin')
  );

-- Policy: Admin/Owner can Delete (Cancel)
create policy "Admins Delete Invites" on project_invites
  for delete using (
    exists (select 1 from projects where id = project_invites.project_id and owner_id = auth.uid()) or
    exists (select 1 from project_members where project_id = project_invites.project_id and user_id = auth.uid() and role = 'admin')
  );

-- Policy: Invited User can Delete (Decline)
create policy "Invited Users Decline Invites" on project_invites
  for delete using (
    email = (select email from auth.users where id = auth.uid())
  );


-- 3. Notifications System (Ensuring table matches previous analysis)
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  actor_id uuid references auth.users(id),
  type text not null, -- 'invite', 'mention', 'system'
  title text,
  message text,
  resource_link text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table notifications enable row level security;

create policy "Users View Own Notifications" on notifications
  for select using (auth.uid() = user_id);

create policy "Users Update Own Notifications" on notifications
  for update using (auth.uid() = user_id);

-- 4. Trigger to Notify User on Invite
create or replace function public.handle_new_invite()
returns trigger as $$
declare
  target_user_id uuid;
  project_name text;
begin
  -- Try to find if the user already exists
  select id into target_user_id from auth.users where email = new.email;
  
  -- Get project name
  select name into project_name from projects where id = new.project_id;

  if target_user_id is not null then
    insert into notifications (user_id, actor_id, type, title, message, resource_link)
    values (
      target_user_id,
      new.invited_by,
      'invite',
      'Nueva Invitación a Proyecto',
      'Has sido invitado a unirte al proyecto ' || coalesce(project_name, 'Desconocido'),
      '/proyectos' -- General link, or maybe dashboard
    );
  end if;
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid duplication error on re-run
drop trigger if exists on_invite_created on project_invites;

create trigger on_invite_created
  after insert on project_invites
  for each row execute procedure public.handle_new_invite();


-- 5. RPC to Accept Invitation
create or replace function accept_project_invite(invite_id bigint)
returns boolean
language plpgsql security definer
as $$
declare
  invite_record record;
  current_user_id uuid;
begin
  current_user_id := auth.uid();
  
  -- Fetch invite
  select * into invite_record from project_invites where id = invite_id;
  
  if invite_record is null then
    raise exception 'Invitación no encontrada';
  end if;
  
  -- Verify email matches current user
  if invite_record.email != (select email from auth.users where id = current_user_id) then
    raise exception 'Esta invitación no te pertenece';
  end if;
  
  -- Insert into members
  insert into project_members (project_id, user_id, role, status)
  values (invite_record.project_id, current_user_id, invite_record.role, 'active')
  on conflict (project_id, user_id) do nothing; -- Just in case
  
  -- Delete invite
  delete from project_invites where id = invite_id;
  
  return true;
end;
$$;
