-- MESSAGING AND NOTIFICATIONS SYSTEM

-- 1. MESSAGES TABLE
create table if not exists messages (
  id bigint generated by default as identity primary key,
  content text not null,
  sender_id uuid references auth.users(id) not null,
  
  -- Context: Project Chat OR Direct Message
  project_id bigint references projects(id) on delete cascade,
  recipient_id uuid references auth.users(id),
  
  -- Metadata
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  read_at timestamp with time zone, -- meaningful for DMs
  
  -- Constraint: Must belong to a project OR be a DM (recipient_id)
  constraint message_context_check check (
    (project_id is not null and recipient_id is null) or 
    (project_id is null and recipient_id is not null)
  )
);

-- 2. NOTIFICATIONS TABLE
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null, -- Who receives it
  actor_id uuid references auth.users(id),         -- Who triggered it (optional)
  
  type text not null, -- 'mention', 'message', 'task_assigned', 'system'
  title text,
  message text,
  resource_link text, -- e.g., '/projects/1/tasks/5'
  
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS POLICIES

alter table messages enable row level security;
alter table notifications enable row level security;

-- MESSAGES POLICIES

-- Policy: Select (View) Messages
-- 1. Project Messages: User must be a member of the project OR owner.
-- 2. Direct Messages: User must be sender OR recipient.
create policy "View messages" on messages
  for select using (
    (project_id is not null and (
      exists (select 1 from project_members where project_id = messages.project_id and user_id = auth.uid()) or
      exists (select 1 from projects where id = messages.project_id and owner_id = auth.uid())
    ))
    or
    (recipient_id is not null and (
      auth.uid() = sender_id or auth.uid() = recipient_id
    ))
  );

-- Policy: Insert Messages
-- 1. Project Messages: User must be a member of the project OR owner.
-- 2. Direct Messages: User can send to anyone (for now, or restrict if needed).
create policy "Insert messages" on messages
  for insert with check (
    auth.uid() = sender_id and (
      (project_id is not null and (
        exists (select 1 from project_members where project_id = messages.project_id and user_id = auth.uid()) or
        exists (select 1 from projects where id = messages.project_id and owner_id = auth.uid())
      ))
      or
      (recipient_id is not null) -- Basic DM permission
    )
  );

-- Policy: Update content (Optional, e.g., edit message) - Let's allow sender to edit for now? 
-- Actually, let's keep it immutable for MVP or only allow sender.
create policy "Update own messages" on messages
  for update using (auth.uid() = sender_id);


-- NOTIFICATIONS POLICIES

-- Policy: View Own Notifications
create policy "View own notifications" on notifications
  for select using (auth.uid() = user_id);

-- Policy: Update Own Notifications (Mark as read)
create policy "Update own notifications" on notifications
  for update using (auth.uid() = user_id);

-- Policy: Insert Notifications
-- Usually backend/triggers insert, but if we do client-side triggering (e.g. from chat service), we need this.
-- Allow authenticated users to create notifications for others (e.g. mentions).
create policy "Insert notifications" on notifications
  for insert with check (auth.role() = 'authenticated'); 
  -- Ideally restrict so you can't spam, but ok for MVP trusted users.

