$file = 'task_to_humanize_pass2.html'
$content = Get-Content $file -Raw -Encoding UTF8

$pass1 = $content -replace 'hizo unas gafas', 'creó unas gafas'
$pass1 = $pass1 -replace 'bota plata', 'invierte dinero'
$pass1 = $pass1 -replace 'hicieron cosas juntas', 'colaboraron'
$pass1 = $pass1 -replace 'tirados en el cajón', 'guardados'
$pass1 = $pass1 -replace 'junta antigua', 'alianza histórica'
$pass1 = $pass1 -replace 'destrozar el diseño', 'desafiar el diseño'
$pass1 = $pass1 -replace 'Mover las cosas', 'Modificar los detalles'
$pass1 = $pass1 -replace 'sirven harto', 'son funcionales'
$pass1 = $pass1 -replace 'estas fábricas se juntaron', 'estas marcas se unieron'
$pass1 = $pass1 -replace 'cuestan un ojo de la cara', 'tienen un alto valor'
$pass1 = $pass1 -replace 'armaron esto', 'diseñaron esto'
$pass1 = $pass1 -replace 'cosían ropa', 'diseñaban moda'
$pass1 = $pass1 -replace 'chucherías', 'accesorios'
$pass1 = $pass1 -replace 'sacaron ropa fina de golpe', 'lanzaron moda exclusiva de pronto'
$pass1 = $pass1 -replace 'Nadie pela', 'Pocos prestan atención a'
$pass1 = $pass1 -replace 'trepan el precio', 'elevan el precio'
$pass1 = $pass1 -replace 'se agandallaron', 'acapararon'
$pass1 = $pass1 -replace 'hacer locuras', 'innovar'
$pass1 = $pass1 -replace 'sacaron dos modelos feos', 'lanzaron dos modelos singulares'
$pass1 = $pass1 -replace 'topas', 'reconoces'
$pass1 = $pass1 -replace 'aguantan trancazos', 'resisten impactos'
$pass1 = $pass1 -replace 'lupa de tianguis', 'lupa de precisión'
$pass1 = $pass1 -replace 'oro chido', 'oro genuino'
$pass1 = $pass1 -replace 'Torcieron las patas', 'Curvaron las varillas'
$pass1 = $pass1 -replace 'Volaron el plástico corriente', 'Eliminaron el plástico común'
$pass1 = $pass1 -replace 'ni a palos lo ves', 'apenas se nota'
$pass1 = $pass1 -replace 'embarraron dorado', 'aplicaron dorado'
$pass1 = $pass1 -replace 'a lo bruto', 'con fuerza'
$pass1 = $pass1 -replace 'material duro', 'material resistente'
$pass1 = $pass1 -replace 'El fierro tapa', 'El metal cubre'
$pass1 = $pass1 -replace 'machucan el vidrio', 'sujetan el cristal'
$pass1 = $pass1 -replace 'se chuecan rápido', 'se deforman rápido'
$pass1 = $pass1 -replace 'Las traes puestas', 'Las llevas puestas'
$pass1 = $pass1 -replace 'Te metes a la casa', 'Ingresas al hogar'
$pass1 = $pass1 -replace 'Te vas pa la nieve', 'Vas a la nieve'
$pass1 = $pass1 -replace 'plástico corriente', 'plástico común'
$pass1 = $pass1 -replace 'páginas chafas', 'sitios dudosos'
$pass1 = $pass1 -replace 'no te tranzas', 'evitas fraudes'
$pass1 = $pass1 -replace 'suenan a juguete', 'suenan frágiles'
$pass1 = $pass1 -replace 'ir al jale', 'ir al trabajo'
$pass1 = $pass1 -replace 'los cates', 'los golpes'
$pass1 = $pass1 -replace 'en friega', 'rápido'
$pass1 = $pass1 -replace 'se ven perronas', 'lucen increíbles'
$pass1 = $pass1 -replace 'plástico gacho', 'plástico endeble'
$pass1 = $pass1 -replace 'Son unas piedrotas', 'Son muy sólidas'
$pass1 = $pass1 -replace 'Están gorditas', 'Son robustas'
$pass1 = $pass1 -replace 'zampan cables', 'integran cables'
$pass1 = $pass1 -replace 'este jale', 'este negocio'
$pass1 = $pass1 -replace 'le hallan a la ropa', 'dominan la moda'
$pass1 = $pass1 -replace 'jala para empezar', 'funciona para empezar'
$pass1 = $pass1 -replace 'Me laten un buen', 'Me agradan mucho'
$pass1 = $pass1 -replace 'quedar al tiro', 'quedar impecable'
$pass1 = $pass1 -replace 'solazo', 'sol intenso'
$pass1 = $pass1 -replace 'fierro del montón', 'metal estándar'
$pass1 = $pass1 -replace 'al puro pedo', 'a la perfección'
$pass1 = $pass1 -replace 'machín', 'resistente'
$pass1 = $pass1 -replace 'sacar ronchas', 'irritar'
$pass1 = $pass1 -replace 'vidrios andan recios', 'cristales son fuertes'

[IO.File]::WriteAllText('task_surgical_pass1.html', $pass1, [System.Text.Encoding]::UTF8)

$pass2 = $pass1
$pass2 = $pass2 -replace 'dejaron la forma de gota', 'mantuvieron la forma de gota'
$pass2 = $pass2 -replace 'Le clavaron metal', 'Incorporaron metal'
$pass2 = $pass2 -replace 'vende caro', 'cotiza alto'
$pass2 = $pass2 -replace 'volaron', 'se agotaron'
$pass2 = $pass2 -replace 'la tela se empolva', 'la prenda se empolva'
$pass2 = $pass2 -replace 'no te dejes', 'ten precaución'
$pass2 = $pass2 -replace 'hace mucho calor', 'las temperaturas suben'
$pass2 = $pass2 -replace 'no hacen corajes', 'evitan frustraciones'
$pass2 = $pass2 -replace 'la pintura no se cae', 'el acabado perdura'
$pass2 = $pass2 -replace 'El puente doble está macizo', 'El puente doble es robusto'
$pass2 = $pass2 -replace 'Las piratas usan', 'Las falsificaciones usan'
$pass2 = $pass2 -replace 'aguantan recargones', 'soportan presión'
$pass2 = $pass2 -replace 'Manejan lo caliente en fa', 'Gestionan bien el calor'
$pass2 = $pass2 -replace 'Ocupas pinzas', 'Requieren pinzas'

[IO.File]::WriteAllText('task_surgical_pass2.html', $pass2, [System.Text.Encoding]::UTF8)

Write-Host "Done"
