
import React, { useMemo, useState } from 'react';
import { CannibalizationGroup, ComparisonRow, Language } from '../types';
import { LayoutGrid, ClipboardList, CheckCircle, Edit3, Save } from 'lucide-react';
import TaskView from './TaskView';

interface GlobalTaskDashboardProps {
    cannibalizationGroups: CannibalizationGroup[];
    comparisonRows: ComparisonRow[];
    lang: Language;
    onBack: () => void;
    onUpdateRows: (rows: ComparisonRow[]) => void;
    onUpdateGroups: (groups: CannibalizationGroup[]) => void;
}

const GlobalTaskDashboard: React.FC<GlobalTaskDashboardProps> = ({
    cannibalizationGroups,
    comparisonRows,
    lang,
    onBack,
    onUpdateRows,
    onUpdateGroups
}) => {
    const [editorMode, setEditorMode] = useState(false);

    const t = {
        title: lang === 'es' ? 'Lista Maestra de Tareas' : 'Master Task List',
        subtitle: lang === 'es' 
            ? 'Vista unificada de todas las tareas generadas por los módulos de IA.' 
            : 'Unified view of all tasks generated by AI modules.',
        sectionCannibalization: lang === 'es' ? 'Canibalizaciones' : 'Cannibalizations',
        sectionOptimization: lang === 'es' ? 'Optimizaciones Generales' : 'General Optimizations',
        empty: lang === 'es' ? 'No hay tareas pendientes. Ejecuta análisis en los módulos individuales primero.' : 'No pending tasks. Run analysis in individual modules first.'
    };

    const activeCannibalizations = useMemo(() => {
        return cannibalizationGroups.filter(g => 
            g.urls.some(u => u.aiTag && !u.aiTag.includes('KEEP') && !u.aiTag.includes('WINNER'))
        );
    }, [cannibalizationGroups]);

    const activeGenericTasks = useMemo(() => {
        return comparisonRows.filter(r => r.aiDiagnosis && r.aiDiagnosis.status !== 'OPTIMAL');
    }, [comparisonRows]);

    const handleDismissGeneric = (query: string) => {
        const updated = comparisonRows.map(r => {
            if (r.query === query) {
                const { aiDiagnosis, aiActions, aiAnalyzed, ...rest } = r;
                return rest;
            }
            return r;
        });
        onUpdateRows(updated);
    };

    const handleRowUpdate = (updatedRow: ComparisonRow) => {
        const newRows = comparisonRows.map(r => r.query === updatedRow.query ? updatedRow : r);
        onUpdateRows(newRows);
    };

    const handleUrlTagUpdate = (groupQuery: string, url: string, newTag: string) => {
         const updatedGroups = cannibalizationGroups.map(group => {
            if (group.query !== groupQuery) return group;
            
            let newWinner = group.winnerUrl;
            if (newTag.toLowerCase().includes('winner') || newTag.toLowerCase().includes('ganadora')) {
                newWinner = url;
            }

            const updatedUrls = group.urls.map(u => {
                if (u.url === url) {
                    return { ...u, aiTag: newTag };
                }
                return u;
            });

            return { ...group, urls: updatedUrls, winnerUrl: newWinner };
        });
        onUpdateGroups(updatedGroups);
    };

    const isEmpty = activeCannibalizations.length === 0 && activeGenericTasks.length === 0;

    return (
        <div className="max-w-7xl mx-auto px-4 py-8 animate-in fade-in">
            <div className="flex items-center justify-between mb-8">
                <div className="flex items-start gap-4">
                    <button onClick={onBack} className="p-2.5 rounded-xl border border-slate-200 text-slate-500 hover:text-indigo-600 bg-white shadow-sm transition-colors">
                        <LayoutGrid className="w-5 h-5" />
                    </button>
                    <div>
                        <h2 className="text-2xl font-bold text-slate-800 leading-tight flex items-center gap-2">
                            {t.title}
                            <ClipboardList className="w-6 h-6 text-indigo-500" />
                        </h2>
                        <p className="text-sm text-slate-500 mt-1">{t.subtitle}</p>
                    </div>
                </div>

                <button onClick={() => setEditorMode(!editorMode)} className={`flex items-center gap-2 px-3 py-2 rounded-lg text-sm font-medium transition-all ${editorMode ? 'bg-violet-100 text-violet-700 border border-violet-200' : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'}`}>
                    {editorMode ? <Save className="w-4 h-4" /> : <Edit3 className="w-4 h-4" />}{editorMode ? 'Exit Editor' : 'Editor'}
                </button>
            </div>

            {isEmpty ? (
                <div className="text-center py-32 bg-white rounded-xl border-2 border-dashed border-slate-200">
                    <div className="bg-slate-50 p-4 rounded-full inline-block mb-4">
                        <CheckCircle className="w-8 h-8 text-emerald-400" />
                    </div>
                    <p className="text-slate-500 font-medium">{t.empty}</p>
                </div>
            ) : (
                <div className="space-y-12">
                    {activeCannibalizations.length > 0 && (
                        <section>
                            <h3 className="text-lg font-bold text-slate-800 mb-4 px-1 border-l-4 border-rose-500 pl-3">
                                {t.sectionCannibalization}
                                <span className="ml-2 bg-rose-100 text-rose-700 text-xs px-2 py-0.5 rounded-full">{activeCannibalizations.length}</span>
                            </h3>
                            <TaskView 
                                mode="CANNIBALIZATION"
                                groups={activeCannibalizations}
                                lang={lang}
                                isEditorMode={editorMode}
                                onUpdateUrlTag={handleUrlTagUpdate}
                            />
                        </section>
                    )}

                    {activeGenericTasks.length > 0 && (
                        <section>
                            <h3 className="text-lg font-bold text-slate-800 mb-4 px-1 border-l-4 border-indigo-500 pl-3">
                                {t.sectionOptimization}
                                <span className="ml-2 bg-indigo-100 text-indigo-700 text-xs px-2 py-0.5 rounded-full">{activeGenericTasks.length}</span>
                            </h3>
                            <TaskView 
                                mode="GENERIC"
                                rows={activeGenericTasks}
                                lang={lang}
                                isEditorMode={editorMode}
                                onDismiss={handleDismissGeneric}
                                onUpdateRow={handleRowUpdate}
                            />
                        </section>
                    )}
                </div>
            )}
        </div>
    );
};

export default GlobalTaskDashboard;
