export const AVAILABLE_LANGUAGES = [
    { code: 'en', name: 'Inglés', nameEn: 'English', nameEs: 'Inglés', flag: '🇺🇸' },
    { code: 'ca', name: 'Catalán', nameEn: 'Catalan', nameEs: 'Catalán', flag: '🇦🇩' },
    { code: 'cs', name: 'Checo', nameEn: 'Czech', nameEs: 'Checo', flag: '🇨🇿' },
    { code: 'da', name: 'Danés', nameEn: 'Danish', nameEs: 'Danés', flag: '🇩🇰' },
    { code: 'fr', name: 'Francés', nameEn: 'French', nameEs: 'Francés', flag: '🇫🇷' },
    { code: 'it', name: 'Italiano', nameEn: 'Italian', nameEs: 'Italiano', flag: '🇮🇹' },
    { code: 'no', name: 'Noruego', nameEn: 'Norwegian', nameEs: 'Noruego', flag: '🇳🇴' },
    { code: 'pt', name: 'Portugués', nameEn: 'Portuguese', nameEs: 'Portugués', flag: '🇵🇹' },
    { code: 'sv', name: 'Sueco', nameEn: 'Swedish', nameEs: 'Sueco', flag: '🇸🇪' },
    { code: 'de', name: 'Alemán', nameEn: 'German', nameEs: 'Alemán', flag: '🇩🇪' },
    { code: 'nl', name: 'Neerlandés', nameEn: 'Dutch', nameEs: 'Neerlandés', flag: '🇳🇱' },
    { code: 'pl', name: 'Polaco', nameEn: 'Polish', nameEs: 'Polaco', flag: '🇵🇱' },
    { code: 'ro', name: 'Rumano', nameEn: 'Romanian', nameEs: 'Rumano', flag: '🇷🇴' },
    { code: 'es', name: 'Español', nameEn: 'Spanish', nameEs: 'Español', flag: '🇪🇸' },
];
