'use server';

import { GoogleGenerativeAI } from "@google/generative-ai";
import { ImagePlan, AspectRatio, SupportedLanguage, InlineImageCount } from '@/types/images';
import { AI_CONFIG, getGeminiKey } from '@/lib/ai/config';

// Defer initialization to avoid crash if API key is missing on load
const getAI = () => {
    const apiKey = getGeminiKey();
    if (!apiKey) {
        throw new Error("Gemini API Key missing. Please check your environment variables (GEMINI_API_KEY).");
    }
    return new GoogleGenerativeAI(apiKey);
};

export const analyzeTextAndPlanImagesAction = async (
    paragraphs: string[],
    instructions: string = "",
    language: SupportedLanguage = 'en',
    inlineImageCount: InlineImageCount = 'auto'
): Promise<ImagePlan> => {
    try {
        const genAI = getAI();
        // Use gemini-1.5-flash for planning (it's fast and has JSON mode support)
        const model = genAI.getGenerativeModel({
            model: "gemini-1.5-flash",
        });

        const contentWithIndices = paragraphs.map((p, i) => `[Paragraph ${i}]: ${p}`).join("\n\n");
        const countInstruction = inlineImageCount === 'auto'
            ? "Identify 2 to 4 strategic locations within the text where an inline image would significantly enhance understanding."
            : `Identify EXACTLY ${inlineImageCount} locations within the text for inline images.`;

        let langInstruction = language === 'es' ? `
    OUTPUT RULES FOR SPANISH (Español):
    1. METADATA: 'altText', 'title', and 'rationale' MUST be in Spanish.
    2. FILENAMES: MUST be in Spanish (kebab-case).
    3. PROMPTS (CRITICAL): Write the visual description in English for the AI generator. Avoid text in images.
    ` : "OUTPUT RULE: All text fields must be in English.";

        const prompt = `
    You are an expert blog editor and SEO specialist. 
    
    TASK:
    1. Analyze the article to identify the "Core Value Proposition".
    2. Create a 'Featured Image' plan.
    3. ${countInstruction}
    4. For each image, write a detailed English prompt for an AI image generator.
    5. Generate SEO-optimized metadata.

    ${langInstruction}

    USER CUSTOM GUIDELINES:
    ${instructions ? `Follow these: "${instructions}"` : "Style: High quality, professional blog aesthetics."}

    ARTICLE TEXT:
    ${contentWithIndices}

    Return the result in JSON format matching this schema:
    {
        "featuredImage": { "prompt": string, "filename": string, "rationale": string, "altText": string, "title": string },
        "inlineImages": [
            { "paragraphIndex": number, "prompt": string, "filename": string, "rationale": string, "altText": string, "title": string }
        ]
    }
    `;

        const result = await model.generateContent({
            contents: [{ role: 'user', parts: [{ text: prompt }] }],
            generationConfig: {
                temperature: 0.3,
                responseMimeType: "application/json"
            }
        });

        const responseText = result.response.text();
        if (!responseText) throw new Error("No plan generated by Gemini.");

        return JSON.parse(responseText) as ImagePlan;
    } catch (error: any) {
        console.error("[SERVER ACTION ERROR] analyzeTextAndPlanImagesAction:", error);
        throw new Error(error.message || "Failed to analyze text.");
    }
};

const getImagen4AspectRatio = (ratio: AspectRatio): string => {
    switch (ratio) {
        case '16:9': return '16:9';
        case '9:16': return '9:16';
        case '4:3': return '4:3';
        case '3:4': return '3:4';
        case '1:1': return '1:1';
        default: return '1:1';
    }
};

export const generateImageAction = async (
    prompt: string,
    modelId: string,
    aspectRatio: AspectRatio = '16:9',
    customWidth?: number,
    customHeight?: number
): Promise<string> => {
    try {
        // Standard Imagen 4 is not available via standard @google/generative-ai SDK easily without vertex
        // However, Gemini 1.5/2.0 can generate images via 'responseModalities' if enabled.
        // But for SIMPLICITY and because we want to use the best model available:

        // If the user selected an 'imagen' model, and we are using @google/generative-ai, 
        // it might fail if that specific model isn't enabled for the AI SDK.
        // We'll map the IDs to ensure they work with the SDK.

        const effectiveModelId = modelId.includes('imagen') ? 'imagen-3' : modelId;

        const genAI = getAI();
        const model = genAI.getGenerativeModel({ model: effectiveModelId });

        // Note: Image generation in @google/generative-ai is usually handled via multimodal parts 
        // but for some specific tiers/regions it's different.
        // If this fails, we will fallback to a clear error message.

        const result = await model.generateContent({
            contents: [{ role: 'user', parts: [{ text: prompt }] }],
            generationConfig: {
                // @ts-ignore - responseModalities is a newer addition to some SDK versions
                responseModalities: ["IMAGE"]
            }
        });

        const candidates = result.response.candidates;
        if (!candidates || candidates.length === 0) {
            throw new Error("Safety filters blocked the image generation or model not supported.");
        }

        for (const part of candidates[0].content?.parts || []) {
            if (part.inlineData && part.inlineData.data) {
                return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
            }
        }

        throw new Error("No image data found in Gemini response. Ensure your API key has access to image generation models.");
    } catch (error: any) {
        console.error("[SERVER ACTION ERROR] generateImageAction:", error);
        throw new Error(error.message || "Failed to generate image.");
    }
};
