-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- 1. Ensure content_drafts table exists
create table if not exists content_drafts (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  title text,
  html_content text,
  strategy_data jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Ensure seo_reports table exists
create table if not exists seo_reports (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  domain text,
  report_data jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Add sharing columns to content_drafts
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'content_drafts' and column_name = 'share_token') then
    alter table content_drafts add column share_token uuid default uuid_generate_v4();
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'content_drafts' and column_name = 'public_access_level') then
    alter table content_drafts add column public_access_level text check (public_access_level in ('none', 'view', 'edit')) default 'none';
  end if;
end $$;

-- 4. Add sharing columns to seo_reports
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'seo_reports' and column_name = 'share_token') then
    alter table seo_reports add column share_token uuid default uuid_generate_v4();
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'seo_reports' and column_name = 'public_access_level') then
    alter table seo_reports add column public_access_level text check (public_access_level in ('none', 'view', 'edit')) default 'none';
  end if;
end $$;

-- 5. Add sharing columns to projects
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'projects' and column_name = 'share_token') then
    alter table projects add column share_token uuid default uuid_generate_v4();
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'projects' and column_name = 'public_access_level') then
    alter table projects add column public_access_level text check (public_access_level in ('none', 'view', 'edit')) default 'none';
  end if;
end $$;

-- 6. Add sharing columns to tasks
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'tasks' and column_name = 'share_token') then
    alter table tasks add column share_token uuid default uuid_generate_v4();
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'tasks' and column_name = 'public_access_level') then
    alter table tasks add column public_access_level text check (public_access_level in ('none', 'view', 'edit')) default 'none';
  end if;
end $$;

-- 7. RLS Policies for sharing

-- content_drafts
alter table content_drafts enable row level security;

-- Policy: Users can view own drafts
drop policy if exists "Users can view own drafts" on content_drafts;
create policy "Users can view own drafts" on content_drafts
  for select using (auth.uid() = user_id);

-- Policy: Users can update own drafts
drop policy if exists "Users can update own drafts" on content_drafts;
create policy "Users can update own drafts" on content_drafts
  for update using (auth.uid() = user_id);

-- Policy: Users can delete own drafts
drop policy if exists "Users can delete own drafts" on content_drafts;
create policy "Users can delete own drafts" on content_drafts
  for delete using (auth.uid() = user_id);

-- Policy: Users can insert own drafts
drop policy if exists "Users can insert own drafts" on content_drafts;
create policy "Users can insert own drafts" on content_drafts
  for insert with check (auth.uid() = user_id);

-- Policy: Public access (View)
drop policy if exists "Public view shared drafts" on content_drafts;
create policy "Public view shared drafts" on content_drafts
  for select using (public_access_level = 'view' or public_access_level = 'edit');

-- Policy: Public access (Edit)
drop policy if exists "Public edit shared drafts" on content_drafts;
create policy "Public edit shared drafts" on content_drafts
  for update using (public_access_level = 'edit');


-- seo_reports
alter table seo_reports enable row level security;

-- Policy: Users can view own reports
drop policy if exists "Users can view own reports" on seo_reports;
create policy "Users can view own reports" on seo_reports
  for select using (auth.uid() = user_id);

-- Policy: Users can delete own reports
drop policy if exists "Users can delete own reports" on seo_reports;
create policy "Users can delete own reports" on seo_reports
  for delete using (auth.uid() = user_id);

-- Policy: Users can insert own reports
drop policy if exists "Users can insert own reports" on seo_reports;
create policy "Users can insert own reports" on seo_reports
  for insert with check (auth.uid() = user_id);

-- Policy: Public access (View)
drop policy if exists "Public view shared reports" on seo_reports;
create policy "Public view shared reports" on seo_reports
  for select using (public_access_level = 'view' or public_access_level = 'edit');


-- projects
-- (Existing policies cover owner access, we just add public access)
drop policy if exists "Public view shared projects" on projects;
create policy "Public view shared projects" on projects
  for select using (public_access_level = 'view' or public_access_level = 'edit');


-- tasks
-- (Existing policies cover project members, we add public access)
drop policy if exists "Public view shared tasks" on tasks;
create policy "Public view shared tasks" on tasks
  for select using (public_access_level = 'view' or public_access_level = 'edit');
